// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASbntt7D18NiYXg3hjDsg3-4ruJ3b9bcU',
    appId: '1:242452055744:web:1ac74173c12e10028b8f25',
    messagingSenderId: '242452055744',
    projectId: 'food-delivery-5ba6f',
    authDomain: 'food-delivery-5ba6f.firebaseapp.com',
    databaseURL: 'https://food-delivery-5ba6f-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-5ba6f.appspot.com',
    measurementId: 'G-Y5SGQES85T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwuS9rjgMv-xv9lHtsSrWk-xf2kFtwaso',
    appId: '1:242452055744:android:8dfbe2b0eb2b7b448b8f25',
    messagingSenderId: '242452055744',
    projectId: 'food-delivery-5ba6f',
    databaseURL: 'https://food-delivery-5ba6f-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-5ba6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9YvuwLsfxx_wBzLplS2pzl-g8AMWSngo',
    appId: '1:242452055744:ios:e7721f5e206378668b8f25',
    messagingSenderId: '242452055744',
    projectId: 'food-delivery-5ba6f',
    databaseURL: 'https://food-delivery-5ba6f-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-5ba6f.appspot.com',
    androidClientId: '242452055744-ek4vj8ih4jnu7t794ibkhmj18m2ilche.apps.googleusercontent.com',
    iosClientId: '242452055744-dvivohb5rhpu38de8st0ucmc37ua8v76.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
